name: Trigger on github-actions-producer
on:
  workflow_dispatch:
jobs:
  trigger-producer:
    name: "Trigger on producer"
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: 3ygun/github-actions-destination
          event-type: general-commit
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
